let songs = [
  {
    name: "Alizee - Lolita",
    artist: "Alizee",
    img: "img1-min",
    audio: "music1",
  },
  {
    name: "Angy Kreyda - Vrazhe",
    artist: "Angy Kreyda",
    img: "img2-min",
    audio: "music2",
  },
  {
    name: "David Usher - Black Black Heart",
    artist: "David Usher",
    img: "img3-min",
    audio: "blackblackheart",
  },
  {
    name: "Red Hot Chilly Peppers - Californication",
    artist: "Red Hot Chilly Peppers",
    img: "img4-min",
    audio: "californication",
  },
  {
    name: "Cranberries - Zombie",
    artist: "Cranberries",
    img: "img5-min",
    audio: "cranberrieszombie",
  },
  {
    name: "Dido - Hunter",
    artist: "Dido",
    img: "img6-min",
    audio: "didohunter",
  },
  {
    name: "Amy Winehouse - Back to Black",
    artist: "Amy Winehouse",
    img: "img7-min",
    audio: "emiuajnhausbacktoblack",
  },
  {
    name: "Amy Winehouse - I'm no Good",
    artist: "Amy Winehouse",
    img: "img8-min",
    audio: "emiyouknowimnogood",
  },
  {
    name: "Lady Gaga - Bloody Mary",
    artist: "Lady Gaga",
    img: "img9-min",
    audio: "ladygagabloodymary",
  },
  {
    name: "Lana del Ray - Cola",
    artist: "Lana del Ray",
    img: "img10-min",
    audio: "lanadelreycola",
  },
  {
    name: "Lana del Ray - Body Electric",
    artist: "Lana del Ray",
    img: "img11-min",
    audio: "lanadereybodyelectric",
  },
  {
    name: "Machine Gun Kelly feat Naomi Wild - Glashouse",
    artist: "Machine Gun Kelly feat Naomi Wild",
    img: "img12-min",
    audio: "machinegunkellyglashousefeatnaomiwild",
  },
  {
    name: "Max Barskih - Don't fu*k with Ukraine",
    artist: "Max Barskih",
    img: "img13-min",
    audio: "maxdon'tfuckwithukraine",
  },
  {
    name: "The Prodigy - Medusas Path",
    artist: "The Prodigy",
    img: "img14-min",
    audio: "medusaspathaono",
  },
  {
    name: "Merilyn Manson - Mobscene",
    artist: "Merilyn Manson",
    img: "img15-min",
    audio: "merlynobsene",
  },
  {
    name: "Miley Cyrus - Flowers",
    artist: "Flowers",
    img: "img16-min",
    audio: "mileycyrusflowers",
  },
  {
    name: "Nancy Sinatra - Bang Bang",
    artist: "Nancy Sinatra",
    img: "img17-min",
    audio: "nancysinatrabangbangmybabyshotmedown",
  },
  {
    name: "Guano Apes - Open Your Mind",
    artist: "Guano Apes",
    img: "img18-min",
    audio: "openyoureyes",
  },
  {
    name: "The Prodigy - Diesel Power",
    artist: "The Prodigy",
    img: "img19-min",
    audio: "prodigydieselpower",
  },
  {
    name: "Rammstein - Amour",
    artist: "Rammstein",
    img: "img20-min",
    audio: "rammsteinamour",
  },
  {
    name: "Rammstein - Donaukinder",
    artist: "Rammstein",
    img: "img21-min",
    audio: "rammstein-donaukinder",
  },
  {
    name: "Rammstein - Angel",
    artist: "Rammstein",
    img: "img22-min",
    audio: "rammsteinengel",
  },
  {
    name: "Rammstein - Feuer und Wasser",
    artist: "Rammstein",
    img: "img23-min",
    audio: "rammsteinfeuerundwasser",
  },
  {
    name: "Rammstein - Deutschland",
    artist: "Rammstein",
    img: "img24-min",
    audio: "rammsteinrdeutschland",
  },
  {
    name: "Rammstein - Rosenrot",
    artist: "Rammstein",
    img: "img25-min",
    audio: "rammsteinrosenrot",
  },
  {
    name: "Jay-Jay Johanson - On The Radio",
    artist: "Jay-Jay Johanson",
    img: "img26-min",
    audio: "jayjayjohansonontheradio",
  },
  {
    name: "Sting - Shape of My Heart",
    artist: "Sting",
    img: "img27-min",
    audio: "shapeofmyheart",
  },
  {
    name: "Stromae - Sant",
    artist: "Stromae",
    img: "img28-min",
    audio: "stromaesant",
  },
  {
    name: "Lana del Ray - Summertime Sadness",
    artist: "Lana del Ray",
    img: "img29-min",
    audio: "summertimesadness",
  },
  {
    name: "The Doors - People are Strange",
    artist: "The Doors",
    img: "img30-min",
    audio: "thedoorspeoplearestrange",
  },
  {
    name: "Queen - Show Must Go On",
    artist: "Rammstein",
    img: "img31-min",
    audio: "theshowmustgoon",
  },
];