let songs = [
  {
    name: "Alizee - Lolita",
    artist: "Alizee",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "music1",
  },
  {
    name: "Angy Kreyda - Vrazhe",
    artist: "Angy Kreyda",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "music2",
  },
  {
    name: "David Usher - Black Black Heart",
    artist: "David Usher",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "blackblackheart",
  },
  {
    name: "Red Hot Chilly Peppers - Californication",
    artist: "Red Hot Chilly Peppers",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "californication",
  },
  {
    name: "Cranberries - Zombie",
    artist: "Cranberries",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "cranberrieszombie",
  },
  {
    name: "Dido - Hunter",
    artist: "Dido",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "didohunter",
  },
  {
    name: "Amy Winehouse - Back to Black",
    artist: "Amy Winehouse",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "emiuajnhausbacktoblack",
  },
  {
    name: "Amy Winehouse - I'm no Good",
    artist: "Amy Winehouse",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "emiyouknowimnogood",
  },
  {
    name: "Lady Gaga - Bloody Mary",
    artist: "Lady Gaga",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "ladygagabloodymary",
  },
  {
    name: "Lana del Ray - Cola",
    artist: "Lana del Ray",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "lanadelreycola",
  },
  {
    name: "Lana del Ray - Body Electric",
    artist: "Lana del Ray",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "lanadereybodyelectric",
  },
  {
    name: "Machine Gun Kelly feat Naomi Wild - Glashouse",
    artist: "Machine Gun Kelly feat Naomi Wild",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "machinegunkellyglashousefeatnaomiwild",
  },
  {
    name: "Max Barskih - Don't fu*k with Ukraine",
    artist: "Max Barskih",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "maxdon'tfuckwithukraine",
  },
  {
    name: "The Prodigy - Medusas Path",
    artist: "The Prodigy",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "medusaspathaono",
  },
  {
    name: "Merilyn Manson - Mobscene",
    artist: "Merilyn Manson",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "merlynobsene",
  },
  {
    name: "Miley Cyrus - Flowers",
    artist: "Flowers",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "mileycyrusflowers",
  },
  {
    name: "Nancy Sinatra - Bang Bang",
    artist: "Nancy Sinatra",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "nancysinatrabangbangmybabyshotmedown",
  },
  {
    name: "Guano Apes - Open Your Mind",
    artist: "Guano Apes",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "openyoureyes",
  },
  {
    name: "The Prodigy - Diesel Power",
    artist: "The Prodigy",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "prodigydieselpower",
  },
  {
    name: "Rammstein - Amour",
    artist: "Rammstein",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "rammsteinamour",
  },
  {
    name: "Rammstein - Donaukinder",
    artist: "Rammstein",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "rammstein-donaukinder",
  },
  {
    name: "Rammstein - Angel",
    artist: "Rammstein",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "rammsteinengel",
  },
  {
    name: "Rammstein - Feuer und Wasser",
    artist: "Rammstein",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "rammsteinfeuerundwasser",
  },
  {
    name: "Rammstein - Deutschland",
    artist: "Rammstein",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "rammsteinrdeutschland",
  },
  {
    name: "Rammstein - Rosenrot",
    artist: "Rammstein",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "rammsteinrosenrot",
  },
  {
    name: "Kazantip music - Anthem of Kazantip",
    artist: "Kazantip music",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "rtemvoicelessgimnkazan",
  },
  {
    name: "Sting - Shape of My Heart",
    artist: "Sting",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "shapeofmyheart",
  },
  {
    name: "Stromae - Sant",
    artist: "Stromae",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "stromaesant",
  },
  {
    name: "Lana del Ray - Summertime Sadness",
    artist: "Lana del Ray",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "summertimesadness",
  },
  {
    name: "The Doors - People are Strange",
    artist: "Rammstein",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "thedoorspeoplearestrange",
  },
  {
    name: "Queen - Show Must Go On",
    artist: "Rammstein",
    img: "https://source.unsplash.com/400x400?mountain",
    audio: "theshowmustgoon",
  },
];